### ISSUE TITLE
Missing 1057 gloss suggestions from wei-por-30-synset.csv

### ISSUE THREAD

**Issue by fcbr** [own-pt/own-pt-api#4]
File `wei-por-30-synset.csv` has 118712 lines, but only 117655 suggestions have been generated from it.  Likely a bug in the file `utils/import-alberto.js`.  We need to identify the root cause of this issue and import the missing suggestions.

**Comment by arademaker** [comment]
Not relevant anymore. We can have better translations with Watson api and gloss corpus.
