### ISSUE TITLE
node crash with invalid synset id

### ISSUE THREAD

**Issue by arademaker** [own-pt/own-pt-api#8]
chalub@wnpt:~/own-pt-api$ node app.js

```
/home/chalub/own-pt-api/solr2cloudant.js:27
  solr.total_rows = solr.response.numFound;
                        ^
TypeError: Cannot read property 'response' of null
 at Object.exports.convertSearchResults
(/home/chalub/own-pt-api/solr2cloudant.js:27:25)
    at /home/chalub/own-pt-api/app.js:442:34
    at IncomingMessage.<anonymous>
(/home/chalub/own-pt-api/node_modules/solr-client/lib/solr.js:780:27)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
    at process._tickCallback (node.js:415:13)
```

**Comment by fcbr** [comment]
Do you remember the steps that made this happen?  I can fix the null reference, but I can't seem to reproduce this locally.

**Comment by fcbr** [comment]
In fact looking at the server logs, it crashed several more times.  We need to come up with the root cause of this. I added some logging on the server to monitor the next crash.

**Comment by fcbr** [comment]
OK, found a repro: http://localhost:3000/get-suggestions/AND%20o

This causes an invalid query to be sent to Sorl.
